### ISSUE TITLE
Disk Utility not showing up?

### ISSUE THREAD

**Issue by Alex-Keyes** [kholia/OSX-KVM#53] opened 2017-02-10 21:01 UTC
After following through the debugging guide and getting the bootloader to load to the installer -  Disk Utility isn't showing up.  According to the readme the solution is to "wait for a few seconds on the "Language Chooser" screen itself without pressing the forward button.".  Following this, I keep waiting in the language chooser screen(anywhere from 5 seconds to a minute or so) and the disk utility option still isn't showing up the options bar.  Could someone define how long I should be waiting or things i should check to make sure there aren't any other things that might be causing this?

**Comment by kholia** [comment] 2017-02-11 05:06
You are opening issues without seeing the previously closed issues. This problem has been solved multiple times now. Please do your "homework" before you open new issues.

**Comment by kholia** [comment] 2017-02-11 05:07
Duplicate of https://github.com/kholia/OSX-KVM/issues/26.

**Closed** 2017-02-11 05:08 UTC
Labels: duplicate, PEBKAC
