### ISSUE TITLE
macOS Sierra installer stuck on "Language chooser"

### ISSUE THREAD

**Issue by Didainius** [kholia/OSX-KVM#37] opened 2016-12-20 10:32 UTC
Anyone had an issue where one simply can't see/find the top toolbar to launch disk utility and terminal?
For me the installer top bar is simply stuck with "Language chooser" at the top even after I choose the language. Siera 10.12.2 release.

**Comment by kholia** [comment] 2016-12-20 11:50
Duplicate of https://github.com/kholia/OSX-KVM/issues/26.

**Closed by kholia** 2016-12-20 11:50 UTC
