### ISSUE TITLE
Dont_Steal_Mac_OS_X while booting the installer

### ISSUE THREAD

**Issue by ArsenArsen** [kholia/OSX-KVM#73] opened 2017-05-02 21:01 UTC
While booting the installer I get the Dont_Steal_Mac_OS_X error. I've looked around the repository for the fixes but all I found required me to access root, or have a partitioned virtual drive, neither of which I have. My setup is using virt-manager but I tried and failed with `boot*.sh` scripts.

Thanks in advance.

**Comment by kholia** [comment] 2017-05-03 04:24
Duplicate of issue https://github.com/kholia/OSX-KVM/issues/64. Do not create duplicate issues.

**Closed by kholia** 2017-05-03 04:24 UTC
Labels: duplicate, invalid
