### ISSUE TITLE
Two mouse arrows

### ISSUE THREAD

**Issue by cmurf** [kholia/OSX-KVM#28] opened 2016-11-06 20:39 UTC
With either El Capitan or Sierra, I see two mouse arrows. One controls the host, the other is in the macOS guest. They're not merged, and they each track at different rates so control is actually rather difficult inside the VM, since the guest mouse arrow tracks slower. I've tried use a tablet device in the VM instead of USB mouse, and also both tablet and USB mouse, but both of those cause the guest mouse arrow to not function at all.

**Comment by kholia** [comment] 2016-11-07 04:34
This issue seems to be a duplicate of https://github.com/kholia/OSX-KVM/issues/17.

**Closed by kholia** 2016-11-07 04:34 UTC
Labels: duplicate
