### ISSUE TITLE
Empty /Kernels folder when generating the ISO image

### ISSUE THREAD

**Issue by jemos** [kholia/OSX-KVM#55] opened 2017-02-26 19:58 UTC
Hi,

I've tried to use create_install_image, it seems to create a good iso but the /Kernels folder is empty. Looking at the log it seems it extracts a kernel from the installer app:

Extracting kernel from Essentials.pkg (very slow step)... 21114747 blocks
OK

When I try to boot it will show:
Can't find boot file: /System/Library/Kernels/kernel

Any idea on what I can do to debug more or what is the issue?

The target is OS X El Sierra.

Thanks,
Jean Mousinho

**Comment by chuckremes** [comment] 2017-02-27 03:19
Try creating the ISO again. Sounds like there was a failure somewhere. You might also want to include a gist (gist.github.com) of the complete log output from the script and add it to this issue.

**Comment by kholia** [comment] 2017-02-28 07:45
@jemos What is the progress on this bug? Are you still facing problems? If the problem is already solved, please mention your solution, and close this bug.

**Comment by kholia** [comment] 2017-03-02 03:13
I am closing this issue due to inactivity.

**Closed by kholia** 2017-03-02 03:13 UTC
