### ISSUE TITLE
processing error - resetting ehci HC

### ISSUE THREAD

**Issue by LLCF** [kholia/OSX-KVM#27] opened 2016-11-05 06:19 UTC
When Ｉ　run
sudo ./boot-macOS.sh
I will get
```
(qemu) ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
```
and the USB mouse cannot be used everywhere

**Comment by kholia** [comment] 2016-11-05 13:05
The "resetting ehci" messages are harmless, I see them too.

The mouse problem seems to be a duplicate of https://github.com/kholia/OSX-KVM/issues/17.

**Closed by kholia** 2016-11-05 13:05 UTC
