### ISSUE TITLE
Position of mouse wrong

### ISSUE THREAD

**Issue by Jan-M-B** [kholia/OSX-KVM#17] opened 2016-10-07 07:52 UTC
Hi,

macOS boots fine so far, but the mouse position is completely wrong, so I am not able to start the Disk Utility in the installation process, any idea?

Jan

**Comment by kholia** [comment] 2016-10-07 09:03
Try using a VNC display, see https://wiki.archlinux.org/index.php/QEMU#vnc page.

https://wiki.archlinux.org/index.php/QEMU#Mouse_integration can help too.

Please report back on what worked for you.

**Comment by Jan-M-B** [comment] 2016-10-07 10:19
Thank you for your fast response :)

Unfortunately both did not work:
I tried VNC and connect with TightVncViewer: same result.
And when I add the "-usbdevice tablet" option, the mouse stops moving at all.

Jan

**Comment by kholia** [comment] 2016-10-07 10:25
Which host OS are you running? Which version of QEMU are you running? Can you give this a go on Ubuntu 16.04 LTS or Fedora 24?

I am out of specific debugging ideas.

**Comment by kholia** [comment] 2016-10-10 04:50
I cannot reproduce this problem on Fedora 24 and hence I am closing this bug. I recommend running latest Ubuntu / Fedora to narrow down (and possibly fix) the problem.

It seems that http://philjordan.eu/osx-virt/ can help in fixing this problem. However, I am not planning on using it myself.

**Closed by kholia** 2016-10-10 04:50 UTC

**Comment by blackleg** [comment] 2016-10-14 15:55
I have the same problem. 
Archlinux Kernel 4.7.6-1-ARCH
Qemu emulator version 2.7.0
Virt Manager 1.4.0

**Comment by cmurf** [comment] 2016-11-07 19:59
OK this bug (actually #28) is happening to me on Fedora 25, so both #17 and #28 can't be closed as if the bug doesn't happen. This should be reopened.

kernel-4.8.6-300.fc25.x86_64
libvirt-libs-2.2.0-1.fc25.x86_64
qemu-common-2.7.0-7.fc25.x86_64
virt-manager-1.4.0-3.fc25.noarch

**Comment by kholia** [comment] 2016-11-08 04:02
Like I said before, try http://philjordan.eu/osx-virt/ with "-usbdevice tablet" option.

**Comment by kholia** [comment] 2016-11-08 05:32
@cmurf Can you try the `boot-macOS.sh` method instead of using virt-manager? Does it make a difference?

**Comment by cmurf** [comment] 2016-11-08 05:50
The driver for macOS at philjordan.eu/osx-virt/ works. Install that driver, shutdown the VM, then delete the Mouse that is type Generic USB Mouse, then add hardware > input > USB Graphics Tablet. 

boot-macOS.sh method doesn't work, there are two mouse arrows.

**Comment by kholia** [comment] 2016-11-08 05:58
Thanks for confirming this.
