### ISSUE TITLE
Created VM does not appear in virt-manager

### ISSUE THREAD

**Issue by msmakhlouf** [kholia/OSX-KVM#14] opened 2016-09-28 10:32 UTC

**Comment by kholia** [comment] 2016-09-28 12:30
I cannot reproduce this problem on Fedora 24.

What steps did you follow? Without further details this issue will be closed as PEBKAC.

**Comment by kholia** [comment] 2016-09-28 16:39
If virt-manager keeps causing trouble, use the boot-macOS.sh method.

**Closed by kholia** 2016-09-28 16:39 UTC
